name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          # go-version-file: 'go.mod'

      - name: Install system deps (CGO / OpenGL)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet ./...

      - name: Test (race + coverage)
        run: go test -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v5
      #   with:
      #     files: ./coverage.out
      #     fail_ci_if_error: true
